### ISSUE TITLE
Add spacing above topic title

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#102]
Between topic title (for example Android) and the horizontal line, we need space to be added (margin or padding)

**Comment by 96RadhikaJadhav** [comment]
@shahednasser Can I work on this issue?

**Comment by shahednasser** [comment]
Hello @96RadhikaJadhav yes go ahead!

**Comment by shahednasser** [comment]
Hello @96RadhikaJadhav are you still working on this?

**Comment by shahednasser** [comment]
Unassigning due to the contributor not responding. This issue now is open to be claimed.

**Comment by ckduane** [comment]
@shahednasser I've got a pull request open to resolve this issue
