### ISSUE TITLE
Change color of horizontal line

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#103]
Make the color of the horizontal line `<hr>` lighter.

**Comment by 96RadhikaJadhav** [comment]
@shahednasser Can I work on this issue?

**Comment by shahednasser** [comment]
Yes @96RadhikaJadhav you can

**Comment by shahednasser** [comment]
Hello @96RadhikaJadhav are you still working on this?

**Comment by shahednasser** [comment]
Unassigning due to the contributor not responding. This issue now is open to be claimed.

**Comment by ckduane** [comment]
@shahednasser I've got a pull request open to resolve this issue
