### ISSUE TITLE
Changes to README

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#116]
We need to change "To contribute, please check out our contribution guide here." to "To add a resource or contribute, please check out our contribution guide here."

**Comment by lem0n4id** [comment]
hey I'd like to do this

**Comment by yash-blmnm** [comment]
Hi @shahednasser, I have added a [Pull Request](https://github.com/shahednasser/awesome-resources/pull/117) to resolve this issue.
