### ISSUE TITLE
Does this repo qualify for Hacktoberfest?

### ISSUE THREAD

**Issue by kr-anurag** [shahednasser/awesome-resources#149]
Hey 
I just wanted to know that does this repo qualifies for Hacktoberfest?

**Comment by shahednasser** [comment]
Hello @kr-anurag . Yes, as this repository has the `hacktoberfest` topic, it qualifies for Hacktoberfest.

Looking forward to your contributions!

**Comment by kr-anurag** [comment]
Hey
Thanks for the answer
gonna make some contributions now
