### ISSUE TITLE
Add LESS resources

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#18]
Add tutorials, articles, videos or any helpful resources about LESS

**Comment by Aniruddha-Shriwant** [comment]
Hey @shahednasser , I would like to work on it

**Comment by shahednasser** [comment]
Yes @Aniruddha-Shriwant go ahead!

**Comment by Aniruddha-Shriwant** [comment]
Hey @shahednasser , I had collected resources regarding LESS that would be helpful even for a beginner 
I want to ask that may I add some links for SASS as its also a CSS preprocessor
also after reading the `CONTRIBUTING.md` I had found that you had arranged all the tutorials in alphabetical order but as this LESS is related to CSS may I add in same CSS section by giving a new LESS title or should I arrange it alphabetically?

**Comment by shahednasser** [comment]
Hello @Aniruddha-Shriwant you can add any type of resources you want! If a topic does not exist you can add it yourself.

I prefer adding LESS and SASS separately, not related to CSS.

**Comment by Aniruddha-Shriwant** [comment]
@shahednasser , okay sure, I will add them separately, and make the PR in Hacktoberfest and thanks to your efforts to maintaining this repository, the resources are very helpful 😊

**Comment by Aniruddha-Shriwant** [comment]
Hey @shahednasser , you may review my PR #21 :)
