### ISSUE TITLE
Fix Rust Link

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#212]
The link for Rust in the table of content has a space between ] and (, so it's not being rendered as a link

**Comment by moazfarrukh** [comment]
can i do this?

**Comment by void-hr** [comment]
Hi @shahednasser I am new to open source and want to contribute (am still in learning phase). I am also a participant of hacktoberfest can you assign me this issue.

**Comment by shahednasser** [comment]
I'm assigning @moazfarrukh for commenting first.

@void-hr you can still contribute by adding resources to this repository.

**Comment by void-hr** [comment]
@shahednasser how can I add resources (like link) after forking and then pull request or I must be assigned first??
