### ISSUE TITLE
Remove the Stanford SOE course link from the Algorithm section

### ISSUE THREAD

**Issue by nis6** [shahednasser/awesome-resources#329]
The two Stanford resources in the Algorithm section open to _section unavailable_

Here are the snapshots
**Part-1**
![image](https://user-images.githubusercontent.com/47380034/148961135-1b2dc858-ab1d-451e-8212-8d2016c154e4.png)
**Part-2**
![image](https://user-images.githubusercontent.com/47380034/148960920-813537e3-7361-4dd6-89ae-00867fe4687f.png)

**Comment by shahednasser** [comment]
Thank you for reporting this. The two links should be removed and you can also submit the new link.

Let me know if you want me to assign you to this

**Comment by arpit-maurya** [comment]
Hi @shahednasser , please can you assign me this, i like to contribute.

**Comment by nis6** [comment]
Yes @shahednasser I'd like to make a PR on this. And @arpit-maurya there are other resources which need updating you can make a commit for them :) I can help you find them if you want.

**Comment by arpit-maurya** [comment]
@nis6  Yes Please ,help me find other resources for PR
