### ISSUE TITLE
Add emojis to explain resources better

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#330]
There is a wide range of resources in this list, with some being podcasts, youtube playlists, blogs, and other variety.

Emojis should be added to each to make it easier to know what the resource is without having to go through it. 

You can find the list of emojis [here](https://gist.github.com/rxaviers/7360908). You can choose whatever emojis you find explanatory to the type, however, all types should have the same emoji (for example, all youtube content should have the same emoji).

A section at the top of the list should explain what each emoji means. Also, a guide on what each emoji is should be added to the [contributing guidelines](https://github.com/shahednasser/awesome-resources/blob/8a48329d36ed1b8cabe09dac3c51c15d4f2b1322/CONTRIBUTING.md) so that contributors can learn how to add emojis when they submit new resources.

**Comment by kady-z** [comment]
Hey! I have been using this resources and to thank you I would like to help you in completing this task although you have self assigned yourself this but let me know if I can help you.

**Comment by shahednasser** [comment]
Thank you but I **just** completed it! Please look into other issues and your help will be appreciated.
