### ISSUE TITLE
Fix hover style of links in dark mode

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#342]
If you hover on links in dark mode the link turns to black. It should turn to a light color (like white) on hover in dark mode

**Comment by Mannuel25** [comment]
> If you hover on links in dark mode the link turns to black. It should turn to a light color (like white) on hover in dark mode

Hello @shahednasser , I'd love to take this up. Kindly assign it to me, thanks.

**Comment by shahednasser** [comment]
Hi @Mannuel25 sure I'll assign you

**Comment by Mannuel25** [comment]
> Hi @Mannuel25 sure I'll assign you

Thank you!
