### ISSUE TITLE
Made scroll behaviour smooth

### ISSUE THREAD

**Issue by 7ORP3DO** [shahednasser/awesome-resources#347]
For good experience smoothly animate the scroll position, instead of a straight jump, when the user  clicks links in [Content](https://shahednasser.github.io/awesome-resources/#content).

**Without Smooth Scroll:**

https://user-images.githubusercontent.com/80192140/150636564-8f412ac5-e306-49c3-b4c7-ce22802f7763.mp4

**With Smooth Scroll:**

https://user-images.githubusercontent.com/80192140/150636585-6f06c5b0-5482-417c-a20f-05e9ce6f4c14.mp4

**Comment by 7ORP3DO** [comment]
Hii @shahednasser, Please assign me on this issue.

**Comment by shahednasser** [comment]
Thank you for this @7ORP3DO that is a nice improvement. I'll assign you so please submit a PR.
