### ISSUE TITLE
Add Note in Contributing Guidelines

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#356]
A lot of link titles include `|` and that causes an error in the rendering of the README on the website (refer to #352 ). We should add a note that all `|` should be replaced with another separator character.

**Comment by mayurstwt** [comment]
I am interested in this issue would you please assign me this ?

**Comment by shahednasser** [comment]
I've assigned you @mayurstwt

**Comment by mayurstwt** [comment]
hey @shahednasser would you please assign me some video or documentation for this issue

**Comment by shahednasser** [comment]
I'm not sure what you mean. You need to make changes in the [contributing guidelines](https://github.com/shahednasser/awesome-resources/blob/25efa6bad9f71fc138525a512174aa4be166c698/CONTRIBUTING.md) and you can check out how to contribute there as well.

**Comment by wasp0094** [comment]
I can take up this issue if it's still up for grabs

**Comment by shahednasser** [comment]
Hi @wasp0094 currently @mayurstwt is working on it.

**Comment by shahednasser** [comment]
Hi @wasp0094  it seems @mayurstwt is not working on this. Do you want to work on it?

**Comment by wasp0094** [comment]
sure, I'll be happy to take it up

**Comment by shahednasser** [comment]
Great @wasp0094 I assigned you
