### ISSUE TITLE
Add GitHub action to verify that all links in the README of a PR are valid

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#415]
At the moment, links in PRs are validated manually. A GitHub action should be added to automate this process.

**Comment by SRADHA-SURESH12** [comment]
Can I work on this issue?

**Comment by ArnabDey1543** [comment]
can you assign me this work

**Comment by ArnabDey1543** [comment]
fixed [GitHub Action - Markdown link check](https://github.com/shahednasser/awesome-resources/pull/530)
Please consider my PR
