### ISSUE TITLE
Change the Position of  FreeHosting Category in readme file and add it to contents section 

### ISSUE THREAD

**Issue by GundaSudarrshan** [shahednasser/awesome-resources#431]
the Free Hosting Category which was below GraphQL section should not be there
It should be in Alphabet F- categories 
and It is also not added into the contents section 

@shahednasser pls assign me this issue I will resolve it

**Comment by GundaSudarrshan** [comment]
@shahednasser  can you add this issue to hacktoberfest so that I would like to contribute to hacktoberfest-22

**Comment by GundaSudarrshan** [comment]
is this eligible for hacktoberfest @shahednasser

**Comment by shahednasser** [comment]
Unfortunately no because it was before October. Only contributions during October count
