### ISSUE TITLE
Fix image in Contribution Guidelines page

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#435]
In the Contribution Guidelines page, the image for "Open Source Love" is broken. Remove the image all together.

**Comment by arthurmatthew** [comment]
I can fix this issue, if that's okay.

**Comment by Dani-Google** [comment]
Hi
This is my first contribution.
**I have removed the image altogether from the Contribution Guideline section**
Please review it.Thank you :)

**Comment by shahednasser** [comment]
I'll assign you @arthurmatthew

**Comment by arthurmatthew** [comment]
> I'll assign you @arthurmatthew

Thanks, I've created a pull request. I noticed that the image loaded fine for me, possibly meaning the image is no longer broken. Do you see this too?

**Comment by shahednasser** [comment]
You're right it's working now 😅 Sorry I'm gonna close the issue and PR. Thanks for working on it!

**Comment by arthurmatthew** [comment]
No problem!
