### ISSUE TITLE
CSS is not applied to many text in the website

### ISSUE THREAD

**Issue by hemanthkumar-21** [shahednasser/awesome-resources#695]
Here the css design green color is not applied to many text forms. and it makes the site to some how disturbed 
![ui-text-color-not-applied-bug](https://github.com/shahednasser/awesome-resources/assets/106808387/58053db2-1ff8-437d-9c4e-2a704b3cc8a5)
 
see the image in design field so many texts doesn't get the color not only in it in many places. 

I will take this issue /assign me

**Comment by draunger** [comment]
I want to solve this issue please assign me as soon as possible

**Comment by AbrahamKiplagat** [comment]
Asign me

**Comment by NivedhaSrinivasan09** [comment]
I would like to address this issue please assign it to me .
